development:
  enabled: true
  host: http://localhost:3000
demo:
  enabled: true
  host: https://demo.trase.earth
indonesiademo:
  enabled: true
  host: https://indonesiademo.trase.earth
production:
  enabled: false
sandbox:
  enabled: true
  host: https://sandbox.trase.earth
staging:
  enabled: true
  host: https://staging.trase.earth
test:
  enabled: false
